service: umzugsauktion-serveless
provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  environment:
    NODE_ENV: dev

plugins:
  - serverless-plugin-typescript 
  - serverless-offline

functions:
  print:
    handler: src/app.printHandler
    events:
      - http:
          path: print/{x}/{y}
          method: get